
---
# tasks file for 2do_parcial

- name: Crear directorios
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

- name: Copiar archivo de datos de alumno
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Copiar archivo de datos de equipo
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
